controller:
  scope:
    enabled: true
    namespace: guytamari
  service:
    type: LoadBalancer
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

rbac:
  scope: true
