apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: { { .Values.namespace } }
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          args:
            - --default-authentication-plugin=mysql_native_password
          envFrom:
            - secretRef:
                name: db-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
