apiVersion: v1
kind: Service
metadata:
  name: wordpress-service--{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress.service.port }}
      targetPort: 80
  type: {{ .Values.wordpress.service.type }}
