apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: guytamari2
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    # - protocol: TCP
    #   port: 3000
    #   targetPort: 3000
  type: ClusterIP
