apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  namespace: guytamari2
spec:
  storageClassName: aws-efs-nitzanim
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
