apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  namespace: guytamari2
spec:
  storageClassName: ebs-sc-guytamari
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
