apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: guytamari2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs-nitzanim
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-043809555c953e8f0
