apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: guytamari
spec:
  storageClassName: ebs-sc-guytamari
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
